" Initialize plugins (vim-plug)
call plug#begin('~/.vim/plugged')
Plug 'jlanzarotta/bufexplorer'
Plug 'scrooloose/nerdtree'
call plug#end()

" NERDTree
map <Leader>nt <ESC>:NERDTree<CR>

" highlight
syntax on
set hlsearch
set number

" indentation
set expandtab
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent

" tensorflow indentation
"highlight ColorColumn ctermbg=lightgrey guibg=lightgrey
"autocmd BufRead,BufNewFile,BufEnter */seq2seq/*  setlocal expandtab softtabstop=2 shiftwidth=2
"autocmd BufRead,BufNewFile,BufEnter */seq2seq/*  setlocal colorcolumn=80
"autocmd BufRead,BufNewFile,BufEnter */t2t/*  setlocal expandtab softtabstop=2 shiftwidth=2
"autocmd BufRead,BufNewFile,BufEnter */t2t/*  setlocal colorcolumn=80
"autocmd Filetype python setlocal expandtab softtabstop=2 shiftwidth=2
"autocmd Filetype python setlocal colorcolumn=80
autocmd Filetype javascript setlocal shiftwidth=2 tabstop=2
autocmd Filetype html setlocal shiftwidth=2 tabstop=2

" Make hidden file when it is closed
set hidden

" shortcut to move to the next message in qiuckfix
map <F3> :cn<CR>

" cscope
if has("cscope")
    " cscope 결과를 quickfix창에서 보기
    "  c: find functions calling this symbol
    "  d: find functions called by this symbol
    "  e: find this egrep patterm
    "  i: find files #including this file
    "  s: find this C symbol
    "  t: find asssignments to
    set cscopequickfix=c-,d-,e-,i-,s-,t-
    " cscopetag
    set cscopetag
    "if filereadable("cscope.out")
    "    cs add cscope.out
    "endif
endif

set ruler

" disable LogiPat. To use ':E'.
let g:loaded_logipat = 1
